config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'

  resources :reports, only: [:index, :new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :time_sheets

  def self.calculate_pay(report_id=nil)
    pay_data = {}
    self.all.each do |emp|
      time_sheets = report_id.present? ? emp.time_sheets.where(report_id: report_id) : emp.time_sheets.all
      if time_sheets.length > 0
        pay_data[emp.id] = {}
        time_sheets.each do |ts|
          mid = ts.date.beginning_of_month + 15.days
          if ts.date < mid
            pay_date = ts.date.beginning_of_month.strftime("%d/%m/%Y") + " - " + (mid - 1.day).strftime("%d/%m/%Y")
          else
            pay_date = mid.strftime("%d/%m/%Y") + " - " + ts.date.end_of_month.strftime("%d/%m/%Y")
          end
          
          amount = ts.total_pay

          if pay_data[emp.id][pay_date].nil?
            pay_data[emp.id][pay_date] = amount
          else
            pay_data[emp.id][pay_date] += amount
          end
        end
      end
    end

    return pay_data
  end
end

app/models/report.rb
require 'csv'

class Report < ApplicationRecord
  has_many :time_sheets

  def self.import(file)
    if File.extname(file.original_filename) == '.csv'

      last_line = find_last_line(file).split(',')
      report_id = last_line.second.to_i

      reports = Report.where(id: report_id)
      if reports.length == 0
        report = Report.create(id: report_id)

        CSV.foreach(file.path, headers: true) do |row|
          next if row['date'] == 'report id'
          
          employee_id = row['employee id']
          employees = Employee.where(id: employee_id)
          employee = employees.length > 0 ? employees[0] : Employee.create!(id: employee_id)

          ts = TimeSheet.new
          ts.employee = employee
          ts.report_id = report_id
          ts.date = row['date']
          ts.hours_worked = row['hours worked']
          ts.job_group = row['job group']
          rate = TimeSheet::RATES[ts.job_group]
          ts.total_pay = ts.hours_worked * rate
          ts.save
        end
        return report_id
      else
        raise StandardError.new("Report #{report_id} already exists.")
      end
    else
      raise StandardError.new("File type '#{file.original_filename}' was not recognised as a csv")
    end
  end

  private

  def self.find_last_line(file)
    f = File.open(file.path)
    f.seek(-2, IO::SEEK_END)
    last_line = nil

    while f.pos > 0
      if f.getc == "\n"
        last_line = f.read
        break
      else
        f.pos -= 2
      end
    end

    last_line = f.read unless last_line
    f.close
    return last_line
  end

end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  belongs_to :employee
  belongs_to :report

  RATES = { "A" => 20.00, "B" => 30.00 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @payment_info = Employee.calculate_pay()
  end

  def new

  end

  def create
    if params[:file].present?
      begin
        report_id = Report.import(params[:file])
        redirect_to report_path(report_id), notice: "Successfully Imported Time Report: #{report_id}"
      rescue => e
        msg = "Import failed. Error: " + e.message
        redirect_to new_report_path, notice: msg
      end
    else
      flash[:notice] = "No file attached for import."
      redirect_to new_report_path
    end
  end

  def show
    @report_id = params[:id]
    @payment_info = Employee.calculate_pay(@report_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeChallengePayroll</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/reports/_payroll_report.html.haml
- if @payment_info.blank?
  %h4 No Pay Period report available.
- else
  %table{border: "2"}
    %thead
      %tr
        %th Employee ID
        %th Pay Period
        %th Amount Paid
    %tbody
      - @payment_info.each do |emp, period|
        - period.sort_by {|k, v| k.split(" ")[0].to_datetime}.each do |period_date, amount|
          %tr
            %td{width: "100px"}= emp
            %td{style: "width: 200px; text-align: center;"}= period_date
            %td{width: "100px"}= number_to_currency(amount)

app/views/reports/index.html.haml
= button_to 'Upload New Time Report', new_report_path, method: :get, style: "margin: 20px 0px;"

%h2 Full Payroll Listing 

= render 'payroll_report'

app/views/reports/new.html.haml
%h2.export-button
  %strong Import Time Report
= form_tag reports_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

app/views/reports/show.html.haml
= button_to 'Full Payroll Listing', reports_path, method: :get, style: "margin: 10px 0px;"
= button_to 'Upload New Time Report', new_report_path, method: :get, style: "margin: 10px 0px;"

%h2 Pay Period Report #{@report_id}

= render 'payroll_report'